POST http://localhost:3333/events
Content-Type: application/json

{
    "title": 1231241,
    "details": 1231,
    "maximumAttendees": 1
}


###

POST http://localhost:3333/events/04015c30-baeb-45ad-8f8d-855a88afd6ae/attendees
Content-Type: application/json

{
    "name": "Schwengber Gui",
    "email": "schwengberdeveloper1020@gmail.com"
}

// http://localhost:3333/
###

GET http://localhost:3333/events/04015c30-baeb-45ad-8f8d-855a88afd6ae


###

// ATTENDEE
GET http://localhost:3333/attendees/1/badge


###

http://localhost:3333/attendees/4/check-in

###


GET http://localhost:3333/events/b6524820-afd4-498d-999a-018d09172a13/attendees